/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBuildSettingsRouteImport } from './routes/_authenticated/build-settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsAppIdRouteImport } from './routes/_authenticated/apps.$appId'
import { Route as ApiPublicAppConfigAppIdRouteImport } from './routes/api/public/app-config.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuildSettingsRoute =
  AuthenticatedBuildSettingsRouteImport.update({
    id: '/build-settings',
    path: '/build-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsAppIdRoute = AuthenticatedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAppConfigAppIdRoute = ApiPublicAppConfigAppIdRouteImport.update({
  id: '/api/public/app-config/$appId',
  path: '/api/public/app-config/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-settings': typeof AuthenticatedBuildSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/app-config/$appId': typeof ApiPublicAppConfigAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-settings': typeof AuthenticatedBuildSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/app-config/$appId': typeof ApiPublicAppConfigAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/build-settings': typeof AuthenticatedBuildSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/app-config/$appId': typeof ApiPublicAppConfigAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/build-settings'
    | '/dashboard'
    | '/apps/$appId'
    | '/api/public/app-config/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/build-settings'
    | '/dashboard'
    | '/apps/$appId'
    | '/api/public/app-config/$appId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/build-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/apps/$appId'
    | '/api/public/app-config/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAppConfigAppIdRoute: typeof ApiPublicAppConfigAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/build-settings': {
      id: '/_authenticated/build-settings'
      path: '/build-settings'
      fullPath: '/build-settings'
      preLoaderRoute: typeof AuthenticatedBuildSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/$appId': {
      id: '/_authenticated/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthenticatedAppsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/app-config/$appId': {
      id: '/api/public/app-config/$appId'
      path: '/api/public/app-config/$appId'
      fullPath: '/api/public/app-config/$appId'
      preLoaderRoute: typeof ApiPublicAppConfigAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuildSettingsRoute: typeof AuthenticatedBuildSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAppsAppIdRoute: typeof AuthenticatedAppsAppIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuildSettingsRoute: AuthenticatedBuildSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAppsAppIdRoute: AuthenticatedAppsAppIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAppConfigAppIdRoute: ApiPublicAppConfigAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
